extend type Booking {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Booking", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`category`. It must match the value of `ServiceCategory`.`id`. See `@ref` for how to customize it.
  """
  categoryId: UUID! @fdc_generated(from: "Booking.category", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`client`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  clientId: UUID! @fdc_generated(from: "Booking.client", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Booking`.`provider`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  providerId: UUID! @fdc_generated(from: "Booking.provider", purpose: IMPLICIT_REF_FIELD)
}
extend type Conversation {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Conversation", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Conversation`.`client`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  clientId: UUID! @fdc_generated(from: "Conversation.client", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Conversation`.`provider`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  providerId: UUID! @fdc_generated(from: "Conversation.provider", purpose: IMPLICIT_REF_FIELD)
}
extend type Message {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Message", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Message`.`conversation`. It must match the value of `Conversation`.`id`. See `@ref` for how to customize it.
  """
  conversationId: UUID! @fdc_generated(from: "Message.conversation", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Message`.`sender`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  senderId: UUID! @fdc_generated(from: "Message.sender", purpose: IMPLICIT_REF_FIELD)
}
extend type Notification {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Notification", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Notification`.`recipient`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  recipientId: UUID! @fdc_generated(from: "Notification.recipient", purpose: IMPLICIT_REF_FIELD)
}
extend type Review {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Review", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`booking`. It must match the value of `Booking`.`id`. See `@ref` for how to customize it.
  """
  bookingId: UUID! @fdc_generated(from: "Review.booking", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Review`.`client`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  clientId: UUID! @fdc_generated(from: "Review.client", purpose: IMPLICIT_REF_FIELD)
}
extend type ServiceCategory {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ServiceCategory", purpose: IMPLICIT_KEY_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type WorkSession {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "WorkSession", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `WorkSession`.`booking`. It must match the value of `Booking`.`id`. See `@ref` for how to customize it.
  """
  bookingId: UUID! @fdc_generated(from: "WorkSession.booking", purpose: IMPLICIT_REF_FIELD)
}
