extend type Booking {
  """
  ✨ List `Review` objects in a one-to-many relationship (where `Review`.`booking` is this object).
  """
  reviews_on_booking(
    """
    Filter condition to narrow down the query results.
    """
    where: Review_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Review_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Review_Having
  ): [Review!]! @fdc_generated(from: "Review.booking", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `WorkSession` objects in a one-to-many relationship (where `WorkSession`.`booking` is this object).
  """
  workSessions_on_booking(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkSession_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkSession_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WorkSession_Having
  ): [WorkSession!]! @fdc_generated(from: "WorkSession.booking", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Booking", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Booking` table.
  """
  _count: Int! @fdc_generated(from: "Booking.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `categoryId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  categoryId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.categoryId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `clientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.clientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `endTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.endTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `providerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  providerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.providerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `serviceLocation` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  serviceLocation_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.serviceLocation", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `startTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.startTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Booking` table where the `totalDurationSeconds` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  totalDurationSeconds_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Booking.totalDurationSeconds", purpose: QUERY_COUNT)
  """
  ✨ Sum the `totalDurationSeconds` field in the `Booking` table.
  """
  totalDurationSeconds_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Booking.totalDurationSeconds", purpose: QUERY_SUM)
  """
  ✨ Average the `totalDurationSeconds` field in the `Booking` table.
  """
  totalDurationSeconds_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Booking.totalDurationSeconds", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `endTime` field in the `Booking` table.
  """
  endTime_min: Timestamp @fdc_generated(from: "Booking.endTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startTime` field in the `Booking` table.
  """
  startTime_min: Timestamp @fdc_generated(from: "Booking.startTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `totalDurationSeconds` field in the `Booking` table.
  """
  totalDurationSeconds_min: Int @fdc_generated(from: "Booking.totalDurationSeconds", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `endTime` field in the `Booking` table.
  """
  endTime_max: Timestamp @fdc_generated(from: "Booking.endTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startTime` field in the `Booking` table.
  """
  startTime_max: Timestamp @fdc_generated(from: "Booking.startTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `totalDurationSeconds` field in the `Booking` table.
  """
  totalDurationSeconds_max: Int @fdc_generated(from: "Booking.totalDurationSeconds", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Booking.id", purpose: ENTITY_ID)
}
extend type Conversation {
  """
  ✨ List `Message` objects in a one-to-many relationship (where `Message`.`conversation` is this object).
  """
  messages_on_conversation(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message.conversation", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Conversation", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Conversation` table.
  """
  _count: Int! @fdc_generated(from: "Conversation.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Conversation` table where the `clientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Conversation.clientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Conversation` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Conversation.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Conversation` table where the `lastMessagePreview` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastMessagePreview_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Conversation.lastMessagePreview", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Conversation` table where the `providerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  providerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Conversation.providerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Conversation` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Conversation.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `updatedAt` field in the `Conversation` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Conversation.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `updatedAt` field in the `Conversation` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Conversation.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Conversation.id", purpose: ENTITY_ID)
}
extend type Message {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Message", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Message` table.
  """
  _count: Int! @fdc_generated(from: "Message.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `content` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  content_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.content", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `conversationId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  conversationId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.conversationId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `senderId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  senderId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.senderId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `timestamp` field in the `Message` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "Message.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `Message` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "Message.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Message.id", purpose: ENTITY_ID)
}
extend type Notification {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Notification", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Notification` table.
  """
  _count: Int! @fdc_generated(from: "Notification.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `isRead` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isRead_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.isRead", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `message` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  message_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.message", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `recipientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  recipientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.recipientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Notification` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Notification.title", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Notification` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Notification.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Notification` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Notification.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Notification.id", purpose: ENTITY_ID)
}
extend type Review {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Review", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Review` table.
  """
  _count: Int! @fdc_generated(from: "Review.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Review` table where the `bookingId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bookingId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Review.bookingId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Review` table where the `clientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Review.clientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Review` table where the `comment` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  comment_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Review.comment", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Review` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Review.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Review` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Review.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Review` table where the `rating` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  rating_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Review.rating", purpose: QUERY_COUNT)
  """
  ✨ Sum the `rating` field in the `Review` table.
  """
  rating_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Review.rating", purpose: QUERY_SUM)
  """
  ✨ Average the `rating` field in the `Review` table.
  """
  rating_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Review.rating", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Review` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Review.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `rating` field in the `Review` table.
  """
  rating_min: Int @fdc_generated(from: "Review.rating", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Review` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Review.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `rating` field in the `Review` table.
  """
  rating_max: Int @fdc_generated(from: "Review.rating", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Review.id", purpose: ENTITY_ID)
}
extend type ServiceCategory {
  """
  ✨ List `Booking` objects in a one-to-many relationship (where `Booking`.`category` is this object).
  """
  bookings_on_category(
    """
    Filter condition to narrow down the query results.
    """
    where: Booking_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Booking_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Booking_Having
  ): [Booking!]! @fdc_generated(from: "Booking.category", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ServiceCategory", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ServiceCategory` table.
  """
  _count: Int! @fdc_generated(from: "ServiceCategory.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServiceCategory` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServiceCategory.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServiceCategory` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServiceCategory.name", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ServiceCategory.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `Booking` objects in a one-to-many relationship (where `Booking`.`client` is this object).
  """
  bookings_on_client(
    """
    Filter condition to narrow down the query results.
    """
    where: Booking_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Booking_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Booking_Having
  ): [Booking!]! @fdc_generated(from: "Booking.client", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Booking` objects in a one-to-many relationship (where `Booking`.`provider` is this object).
  """
  bookings_on_provider(
    """
    Filter condition to narrow down the query results.
    """
    where: Booking_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Booking_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Booking_Having
  ): [Booking!]! @fdc_generated(from: "Booking.provider", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Conversation` objects in a one-to-many relationship (where `Conversation`.`client` is this object).
  """
  conversations_on_client(
    """
    Filter condition to narrow down the query results.
    """
    where: Conversation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Conversation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Conversation_Having
  ): [Conversation!]! @fdc_generated(from: "Conversation.client", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Conversation` objects in a one-to-many relationship (where `Conversation`.`provider` is this object).
  """
  conversations_on_provider(
    """
    Filter condition to narrow down the query results.
    """
    where: Conversation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Conversation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Conversation_Having
  ): [Conversation!]! @fdc_generated(from: "Conversation.provider", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Message` objects in a one-to-many relationship (where `Message`.`sender` is this object).
  """
  messages_on_sender(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message.sender", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Notification` objects in a one-to-many relationship (where `Notification`.`recipient` is this object).
  """
  notifications_on_recipient(
    """
    Filter condition to narrow down the query results.
    """
    where: Notification_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Notification_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Notification_Having
  ): [Notification!]! @fdc_generated(from: "Notification.recipient", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Review` objects in a one-to-many relationship (where `Review`.`client` is this object).
  """
  reviews_on_client(
    """
    Filter condition to narrow down the query results.
    """
    where: Review_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Review_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Review_Having
  ): [Review!]! @fdc_generated(from: "Review.client", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `bio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.bio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `hourlyRate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  hourlyRate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.hourlyRate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.phoneNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `profilePicture` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  profilePicture_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.profilePicture", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.role", purpose: QUERY_COUNT)
  """
  ✨ Sum the `hourlyRate` field in the `User` table.
  """
  hourlyRate_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.hourlyRate", purpose: QUERY_SUM)
  """
  ✨ Average the `hourlyRate` field in the `User` table.
  """
  hourlyRate_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "User.hourlyRate", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `hourlyRate` field in the `User` table.
  """
  hourlyRate_min: Float @fdc_generated(from: "User.hourlyRate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `hourlyRate` field in the `User` table.
  """
  hourlyRate_max: Float @fdc_generated(from: "User.hourlyRate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: ENTITY_ID)
}
extend type WorkSession {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "WorkSession", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `WorkSession` table.
  """
  _count: Int! @fdc_generated(from: "WorkSession.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkSession` table where the `bookingId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bookingId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkSession.bookingId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkSession` table where the `endTimestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endTimestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkSession.endTimestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkSession` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkSession.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkSession` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkSession.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `WorkSession` table where the `startTimestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startTimestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "WorkSession.startTimestamp", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `endTimestamp` field in the `WorkSession` table.
  """
  endTimestamp_min: Timestamp @fdc_generated(from: "WorkSession.endTimestamp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startTimestamp` field in the `WorkSession` table.
  """
  startTimestamp_min: Timestamp @fdc_generated(from: "WorkSession.startTimestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `endTimestamp` field in the `WorkSession` table.
  """
  endTimestamp_max: Timestamp @fdc_generated(from: "WorkSession.endTimestamp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startTimestamp` field in the `WorkSession` table.
  """
  startTimestamp_max: Timestamp @fdc_generated(from: "WorkSession.startTimestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "WorkSession.id", purpose: ENTITY_ID)
}
